[package]
name = "tlss"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustls = { path = "deps/rustls-0.22.1" }
rcgen = "0.12.0"
rand = "0.8.5"